general {
    lock_cmd = pidof hyprlock || hyprlock       # Avoid starting multiple hyprlock instances
    before_sleep_cmd = loginctl lock-session    # Lock before suspending
    after_sleep_cmd = hyprctl dispatch dpms on  # Turn screen on after waking
}

# Suspend the system after 15 minutes of inactivity
listener {
    timeout = 900
    on-timeout = systemctl suspend
}
